[PlankDrawingTheme]
#The roundness of the top corners.
TopRoundness=6
#The roundness of the bottom corners.
BottomRoundness=6
#The thickness (in pixels) of lines drawn.
LineWidth=1
#The color (RGBA) of the outer stroke.
OuterStrokeColor=0;;0;;0;;100
#The starting color (RGBA) of the fill gradient.
FillStartColor=50;;50;;50;;100
#The ending color (RGBA) of the fill gradient.
FillEndColor=50;;50;;50;;200
#The color (RGBA) of the inner stroke.
InnerStrokeColor=50;;50;;50;;0
