#!/bin/sh

if [ "$1" = remove -o "$1" = purge ]; then
  dpkg-divert --remove --rename --package ubuntu-mate-live-settings --divert /usr/share/ubiquity/pixmaps/ubuntu_installed.png.distrib /usr/share/ubiquity/pixmaps/ubuntu_installed.png
  dpkg-divert --remove --rename --package ubuntu-mate-live-settings --divert /usr/share/ubiquity/pixmaps/panel.png.distrib /usr/share/ubiquity/pixmaps/panel.png
fi

#DEBHELPER#
